=== MaximilianKucher/Uni/2.Semester/Informatik_2/workspace/DeklarativeProgrammierung/Rechneruebung3/Rechneruebung3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 	xmlns:xs="http://www.w3.org/2001/XMLSchema"
			xmlns="http://www.example.org/Rechneruebung3"
			targetNamespace="http://www.example.org/Rechneruebung3"
			elementFormDefault="qualified">
		
	<xs:element name="RECHNUNGEN">
        <xs:complexType>
			<xs:sequence>
				<xs:element name="RECHNUNG" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="NAME" type="xs:string" />
										<xs:element name="STRAßE" type="xs:string" />
										<xs:element name="ADRESSE" type="xs:string" />
										<xs:element name="TELEFONNUMMER" type="xs:string" minOccurs="0"/>
										<xs:element name="FAX" type="xs:string" minOccurs="0" />
										<xs:element name="E-MAIL_ADRESSE" type="xs:string" minOccurs="0" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ANREDE" type="xs:string" minOccurs="0" />
										<xs:element name="NAME" type="xs:string" />
										<xs:element name="STRAßE" type="xs:string" />
										<xs:element name="ADRESSE" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="LEISTUNGEN">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="LEISTUNG" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="NUMMER" type="xs:unsignedInt" />
													<xs:element name="WÄHRUNG">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="EUR" />
																<xs:enumeration value="USD" />
																<xs:enumeration value="AUD" />
																<xs:enumeration value="CHF" />
																<xs:enumeration value="GBP" />
																<xs:enumeration value="JPY" />
															</xs:restriction>													
														</xs:simpleType>
													</xs:element>
													<xs:element name="HANDELSÜBLICHER_NAME" type="xs:string" />
													<xs:element name="ANZAHL" type="xs:unsignedInt" minOccurs="0" />
													<xs:element name="DATUM" type="xs:date" minOccurs="0" />
												</xs:sequence>
												<xs:attribute name="MEHRWERTSTEUER" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="STEUERNUMMER">
								<xs:complexType>
									<xs:choice>
										<xs:element name="STEUERNUMMER_UNTERNEHMER" type="xs:unsignedLong"/>
										<xs:element name="UMSATZSTEUER-IDENTIFIKATIONSNUMMER" type="xs:string"/>
									</xs:choice>
								</xs:complexType>	
							</xs:element>
							<xs:element name="AUSSTELLUNGSDATUM" type="xs:date" />
							<xs:element name="RECHNUNGSNUMMER" type="xs:string" />
							<xs:element name="ENTGELD_IN_EURO" type="xs:decimal" />
							<xs:element name="ZAHLUNGSMOEGLICHKEITEN">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DEUTSCHLANDINTERN" minOccurs="0">
											<xs:complexType>
												<xs:all>
													<xs:element name="KONTOINHABER" type="xs:string" minOccurs="0"/>
													<xs:element name="BANK" type="xs:string" minOccurs="0" />
													<xs:element name="BIC" type="xs:string" minOccurs="0"/>
													<xs:element name="IBAN" type="xs:string" minOccurs="0"/>
													<xs:element name="KONTONUMMER" type="xs:unsignedLong" minOccurs="0"/>
													<xs:element name="BLZ" type="xs:unsignedLong" minOccurs="0"/>
												</xs:all>	
											</xs:complexType>
										</xs:element>
										<xs:element name="AUßERHALB_DEUTSCHLANDS" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="KONTONUMMER" type="xs:unsignedInt" />
													<xs:element name="BIC" type="xs:string" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="KRYPTOWAEHRUNG" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="BITCOIN_ADRESSE" type="xs:string" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
    </xs:element>
</xs:schema>

=== MaximilianKucher/Uni/2.Semester/Informatik_2/workspace/DeklarativeProgrammierung/Rechneruebung3/Rechneruebung3.xml
<?xml version="1.0" encoding="UTF-8"?>

<RECHNUNGEN
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://www.example.org/Rechneruebung3"
xsi:schemaLocation="http://www.example.org/Rechneruebung3 Rechneruebung3.xsd">


	<RECHNUNG>
		<NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER>
			<NAME>Kleintier Meier GmbH</NAME>
			<STRAßE>Meierring 3</STRAßE>
			<ADRESSE>81828 Machthausen</ADRESSE>
			<TELEFONNUMMER>0777987987</TELEFONNUMMER>
			<FAX>0777987789</FAX>									<!-- Optionales element -->
			<E-MAIL_ADRESSE>klein.meier@tiere.de</E-MAIL_ADRESSE> 	<!-- Optionales element -->
		</NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER>
		<NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER>
			<NAME>Sybille Sonder-Suttelrau</NAME>
			<STRAßE>Am Süttelbach 17</STRAßE>
			<ADRESSE>77070 Siedelsuderstadt</ADRESSE>
		</NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER>
		<LEISTUNGEN> 												<!-- mindestens eine Leistung -->
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>1</NUMMER>
				<WÄHRUNG>EUR</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Antike Holzwürmer</HANDELSÜBLICHER_NAME>
				<ANZAHL>100</ANZAHL>								<!-- optionales element -->
				<DATUM>2017-01-01</DATUM> 							<!-- Optionales element -->
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>2</NUMMER>
				<WÄHRUNG>EUR</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Holzwurmfutter</HANDELSÜBLICHER_NAME>
				<ANZAHL>1</ANZAHL>
				<DATUM>2017-01-12</DATUM>
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>3</NUMMER>
				<WÄHRUNG>EUR</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Steinlaus, Petrophaga lorioti</HANDELSÜBLICHER_NAME>
				<ANZAHL>1</ANZAHL>
				<DATUM>2017-01-12</DATUM>
			</LEISTUNG>
		</LEISTUNGEN>
		<STEUERNUMMER>
			<STEUERNUMMER_UNTERNEHMER>8812382822</STEUERNUMMER_UNTERNEHMER>
		</STEUERNUMMER>
		<AUSSTELLUNGSDATUM>2017-01-15</AUSSTELLUNGSDATUM>
		<RECHNUNGSNUMMER>657321</RECHNUNGSNUMMER>
		<ENTGELD_IN_EURO>962.22</ENTGELD_IN_EURO>
		<ZAHLUNGSMOEGLICHKEITEN>
			<DEUTSCHLANDINTERN>
				<KONTOINHABER>Kleintier Meier</KONTOINHABER>
				<BANK>Sparkasse Karlsruhe</BANK>
				<KONTONUMMER>987654321</KONTONUMMER>
				<BLZ>66050101</BLZ>
			</DEUTSCHLANDINTERN>
		</ZAHLUNGSMOEGLICHKEITEN>
	</RECHNUNG>
	<RECHNUNG>
		<NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER>
			<NAME>Rochade-La Hoff Pharma GmbH</NAME>
			<STRAßE>An der Chemie 17</STRAßE>
			<ADRESSE>79639 Grenzych-Wahlen</ADRESSE>
			<TELEFONNUMMER>07624666333999</TELEFONNUMMER>
			<FAX>07624666333990</FAX>
		</NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER>
		<NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER>
			<NAME>Dr. med. Cyprian Zottel</NAME>
			<STRAßE>Soddelstrudel 5a</STRAßE>
			<ADRESSE>13023 Zotenheim</ADRESSE>
		</NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER>
		<LEISTUNGEN>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>1</NUMMER>
				<WÄHRUNG>EUR</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Grippemittel "Tumifla"</HANDELSÜBLICHER_NAME>
				<ANZAHL>3</ANZAHL>
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>2</NUMMER>
				<WÄHRUNG>EUR</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Beratung pauschal</HANDELSÜBLICHER_NAME>
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>3</NUMMER>
				<WÄHRUNG>EUR</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Abführmittel "Wech damit"</HANDELSÜBLICHER_NAME>
				<ANZAHL>2</ANZAHL>
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="7%">
				<NUMMER>4</NUMMER>
				<WÄHRUNG>EUR</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Energieriegel "Satto"</HANDELSÜBLICHER_NAME>
				<ANZAHL>2</ANZAHL>
			</LEISTUNG>
		</LEISTUNGEN>
		<STEUERNUMMER>
			<UMSATZSTEUER-IDENTIFIKATIONSNUMMER>DE333666999</UMSATZSTEUER-IDENTIFIKATIONSNUMMER>
		</STEUERNUMMER>
		<AUSSTELLUNGSDATUM>2017-08-08</AUSSTELLUNGSDATUM>
		<RECHNUNGSNUMMER>98-798-7987</RECHNUNGSNUMMER>
		<ENTGELD_IN_EURO>621.94</ENTGELD_IN_EURO>
		<ZAHLUNGSMOEGLICHKEITEN>
			<DEUTSCHLANDINTERN>
				<BANK>Deutsche Bank Lörrach</BANK>
				<BIC>DEUTDE6F683</BIC>
				<IBAN>DE18683700340999666333</IBAN>
			</DEUTSCHLANDINTERN>
		</ZAHLUNGSMOEGLICHKEITEN>
	</RECHNUNG>
	<RECHNUNG>
		<NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER>
			<NAME>Bestattungen Unterberg</NAME>
			<STRAßE>Oberbergweg 5</STRAßE>
			<ADRESSE>43210 Ultursingen</ADRESSE>
			<TELEFONNUMMER>0478777555</TELEFONNUMMER>
			<E-MAIL_ADRESSE>unter@berg.de</E-MAIL_ADRESSE>
		</NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER>
		<NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER>
			<NAME>Familie Urmel</NAME>
			<STRAßE>Ulturenstrasse 764</STRAßE>
			<ADRESSE>43210 Ultursingen</ADRESSE>
		</NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER>
		<LEISTUNGEN>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>1</NUMMER>
				<WÄHRUNG>EUR</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Urne, Eiche massiv</HANDELSÜBLICHER_NAME>
				<ANZAHL>1</ANZAHL>
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>2</NUMMER>
				<WÄHRUNG>EUR</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Ueberfuehrung Krematorium Feuerbach inkl. Begleitpersonal</HANDELSÜBLICHER_NAME>
				<ANZAHL>1</ANZAHL>
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>3</NUMMER>
				<WÄHRUNG>EUR</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Dekoration</HANDELSÜBLICHER_NAME>
				<ANZAHL>1</ANZAHL>
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>4</NUMMER>
				<WÄHRUNG>EUR</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Trauerkarten inkl. Briefmarken</HANDELSÜBLICHER_NAME>
				<ANZAHL>40</ANZAHL>
			</LEISTUNG>
		</LEISTUNGEN>
		<STEUERNUMMER>
			<UMSATZSTEUER-IDENTIFIKATIONSNUMMER>DE987654321</UMSATZSTEUER-IDENTIFIKATIONSNUMMER>
		</STEUERNUMMER>
		<AUSSTELLUNGSDATUM>2017-10-19</AUSSTELLUNGSDATUM>
		<RECHNUNGSNUMMER>89321311</RECHNUNGSNUMMER>
		<ENTGELD_IN_EURO>878.49</ENTGELD_IN_EURO>
		<ZAHLUNGSMOEGLICHKEITEN>
			<DEUTSCHLANDINTERN>
				<IBAN>DE16660501010077889911</IBAN>
			</DEUTSCHLANDINTERN>
			<AUßERHALB_DEUTSCHLANDS>
				<KONTONUMMER>75847683</KONTONUMMER>
				<BIC>UBSWCHZH80H</BIC>
			</AUßERHALB_DEUTSCHLANDS>
			<KRYPTOWAEHRUNG>
				<BITCOIN_ADRESSE>1P82rBiJHDFSav2QrKx1bvdDRVh5QnGkkZ</BITCOIN_ADRESSE>
			</KRYPTOWAEHRUNG>
		</ZAHLUNGSMOEGLICHKEITEN>
	</RECHNUNG>
</RECHNUNGEN>
