=== MaximilianKucher/Uni/2.Semester/Informatik_2/workspace/DeklarativeProgrammierung/Rechneruebung2/Rechneruebung2.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT RECHNUNGEN (RECHNUNG*)>
<!ELEMENT RECHNUNG (NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER,
					NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER, 
					LEISTUNGEN, 
					(STEUERNUMMER_UNTERNEHMER | UMSATZSTEUER-IDENTIFIKATIONSNUMMER), 
					AUSSTELLUNGSDATUM, 
					RECHNUNGSNUMMER, 
					ENTGELD_IN_EURO)>
<!ELEMENT NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER (STRAßE,
													 ADRESSE,
													 TELEFONNUMMER,
													 FAX,
													 (E-MAIL_ADRESSE?))>
<!ELEMENT NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER (STRAßE, ADRESSE)>
<!ELEMENT LEISTUNGEN (LEISTUNG+)>
<!ELEMENT LEISTUNG (NUMMER, WÄHRUNG, HANDELSÜBLICHER_NAME, (ANZAHL?), (DATUM?))>
<!ELEMENT STEUERNUMMER_UNTERNEHMER (#PCDATA)>
<!ELEMENT UMSATZSTEUER-IDENTIFIKATIONSNUMMER (#PCDATA)>
<!ELEMENT AUSSTELLUNGSDATUM (#PCDATA)>
<!ELEMENT RECHNUNGSNUMMER (#PCDATA)>
<!ELEMENT ENTGELD_IN_EURO (#PCDATA)>
<!ELEMENT NUMMER (#PCDATA)>
<!ELEMENT WÄHRUNG (#PCDATA)>
<!ELEMENT HANDELSÜBLICHER_NAME (#PCDATA)>
<!ELEMENT ANZAHL (#PCDATA)>
<!ELEMENT DATUM (#PCDATA)>
<!ELEMENT STRAßE (#PCDATA)>
<!ELEMENT ADRESSE (#PCDATA)>
<!ELEMENT TELEFONNUMMER (#PCDATA)>
<!ELEMENT FAX (#PCDATA)>
<!ELEMENT E-MAIL_ADRESSE (#PCDATA)>

<!ATTLIST NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER NAME CDATA #REQUIRED>
<!ATTLIST NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER NAME CDATA #REQUIRED>
<!ATTLIST LEISTUNG MEHRWERTSTEUER CDATA #REQUIRED>

=== MaximilianKucher/Uni/2.Semester/Informatik_2/workspace/DeklarativeProgrammierung/Rechneruebung2/Rechneruebung2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RECHNUNGEN SYSTEM "Rechneruebung2.dtd">

<RECHNUNGEN>
	<RECHNUNG>
		<NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER NAME="Kleintier Meier GmbH">
			<STRAßE>Meierring 3</STRAßE>
			<ADRESSE>81828 Machthausen</ADRESSE>
			<TELEFONNUMMER>0777987987</TELEFONNUMMER>
			<FAX>0777987789</FAX>
			<E-MAIL_ADRESSE>klein.meier@tiere.de</E-MAIL_ADRESSE> 	<!-- Optionales element -->
		</NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER>
		<NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER NAME="Sybille Sonder-Suttelrau">
			<STRAßE>Am Süttelbach 17</STRAßE>
			<ADRESSE>77070 Siedelsuderstadt</ADRESSE>
		</NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER>
		<LEISTUNGEN> 												<!-- mindestens eine Leistung -->
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>1</NUMMER>
				<WÄHRUNG>Euro</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Antike Holzwürmer</HANDELSÜBLICHER_NAME>
				<ANZAHL>100</ANZAHL>								<!-- optionales element -->
				<DATUM>01.01.2017</DATUM> 							<!-- Optionales element -->
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>2</NUMMER>
				<WÄHRUNG>Euro</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Holzwurmfutter</HANDELSÜBLICHER_NAME>
				<ANZAHL>1</ANZAHL>
				<DATUM>12.01.2017</DATUM>
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>3</NUMMER>
				<WÄHRUNG>Euro</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Steinlaus, Petrophaga lorioti</HANDELSÜBLICHER_NAME>
				<ANZAHL>1</ANZAHL>
				<DATUM>12.01.2017</DATUM>
			</LEISTUNG>
		</LEISTUNGEN>
		<STEUERNUMMER_UNTERNEHMER>8812382822</STEUERNUMMER_UNTERNEHMER>
		<AUSSTELLUNGSDATUM>15.01.2017</AUSSTELLUNGSDATUM>
		<RECHNUNGSNUMMER>657321</RECHNUNGSNUMMER>
		<ENTGELD_IN_EURO>962,22</ENTGELD_IN_EURO>
	</RECHNUNG>
	<RECHNUNG>
		<NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER NAME="Rochade-La Hoff Pharma GmbH">
			<STRAßE>An der Chemie 17</STRAßE>
			<ADRESSE>79639 Grenzych-Wahlen</ADRESSE>
			<TELEFONNUMMER>07624666333999</TELEFONNUMMER>
			<FAX>07624666333990</FAX>
		</NAME_UND_ANSCHRIFT_LEISTENDER_UNTERNEHMER>
		<NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER NAME="Dr. med. Cyprian Zottel">
			<STRAßE>Soddelstrudel 5a</STRAßE>
			<ADRESSE>13023 Zotenheim</ADRESSE>
		</NAME_UND_ANSCHRIFT_LEISTUNGSEMPFÄNGER>
		<LEISTUNGEN>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>1</NUMMER>
				<WÄHRUNG>Euro</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Grippemittel "Tumifla"</HANDELSÜBLICHER_NAME>
				<ANZAHL>3</ANZAHL>
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>2</NUMMER>
				<WÄHRUNG>Euro</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Beratung pauschal</HANDELSÜBLICHER_NAME>
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="19%">
				<NUMMER>3</NUMMER>
				<WÄHRUNG>Euro</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Abführmittel "Wech damit"</HANDELSÜBLICHER_NAME>
				<ANZAHL>2</ANZAHL>
			</LEISTUNG>
			<LEISTUNG MEHRWERTSTEUER="7%">
				<NUMMER>4</NUMMER>
				<WÄHRUNG>Euro</WÄHRUNG>
				<HANDELSÜBLICHER_NAME>Energieriegel "Satto"</HANDELSÜBLICHER_NAME>
				<ANZAHL>2</ANZAHL>
			</LEISTUNG>
		</LEISTUNGEN>
		<UMSATZSTEUER-IDENTIFIKATIONSNUMMER>DE333666999</UMSATZSTEUER-IDENTIFIKATIONSNUMMER>
		<AUSSTELLUNGSDATUM>08.08.2017</AUSSTELLUNGSDATUM>
		<RECHNUNGSNUMMER>98-798-7987</RECHNUNGSNUMMER>
		<ENTGELD_IN_EURO>621,94</ENTGELD_IN_EURO>
	</RECHNUNG>
</RECHNUNGEN>
